<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Ayant_droitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ayant_droitRepository extends \Doctrine\ORM\EntityRepository
{
}
