<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Lieu_travailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lieu_travailRepository extends \Doctrine\ORM\EntityRepository
{
}
