<?php

namespace Cmi\ApiBundle\Repository;

/**
 * ProffessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProffessionRepository extends \Doctrine\ORM\EntityRepository
{
}
