<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Type_contratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_contratRepository extends \Doctrine\ORM\EntityRepository
{
}
