<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Type_patientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_patientRepository extends \Doctrine\ORM\EntityRepository
{
}
